export const GET_CATEGORIES = 'GET_CATEGORIES'
export const CATEGORY_REQUEST_LOADING = 'CATEGORY_REQUEST_LOADING'
export const CATEGORY_REQUEST_ERROR = 'CATEGORY_REQUEST_ERROR'
export const CATEGORY_CANCEL_LOADING = 'CATEGORY_CANCEL_LOADING'
